### ISSUE TITLE
As a developer I want to have an example tutorial. [10]

### ISSUE THREAD

**Issue by dkipping** [HPI-SWA-Teaching/SWT17-Project-11#5]
- [x] tutorial plays out as specified
- [ ] "wrong" interactions dont cause lock out of the system or the tutorial to hang

Steps:
- [x] Step 1: "Welcome to this tutorial! Here, we will teach you how to do basic coding with the Browser in Squeak."
- [x] Step 2: "To open the Browser, click into the world (the background of the squeak window)." (<-- hier wäre ein arrow vielleicht echt cool, aber lassen wir erstmal weg) *menu appears*
- [x] Step 3: [highlight the menu] "Now select the 'Browser' item from the menu"
- [x] Step 4: [highlight the browser] "This is the browser window. It consists of multiple panes"
- [x] Step 5: [highlight the category list pane] "In this pane, the categories are listed. We will go ahead and create our own. Do so by right-clicking into the pane and select "Add Item".
- [x] Step 6: [explanation without highlight under the prompt that asks for your category name] "Go ahead and enter a name for your category, e.g. "CoolCategory". Next, press Confirm." (<-- es wär echt cool hier beim button press auch den wert des input felds abzufangen und zu speichern)
- [x] Step 7: [explanation without highlight in the center of the browser window] "Congratz! You just added the <category name that we saved here> category! Let's create a class next."
- [x] Step 8: [highlight the code pane on the bottom] "Here, specify the class we want to inherit from by replacing "Object" with "Morph". Next, give your class a name by replacing "NameOfSubclass" with e.g. "MyCoolClass". When you're done, hit Ctrl+s.". (<-- wie ihr das speichern abfangt wird auch interessant. entweder muss das browser model angefragt werden oder der key press abgefangen werden)
- [x] Step 8x: [If the subclass is wrong, keep the highlight on the code pane] "Make sure to specify "Morph" as the value before "subclass:"."
- [x] Step 9: [highlight the category pane] "Lastly, to create a method, click into the category pane. Each of your methods can be sorted into a category in order to make it easier to find."
- [x] Step 10: [highlight the code pane] "What you see in this window now is the typical boilerplate for a method. Replace all its contents with our constructor method's name: initialize. Then hit Ctrl+s again to save the method."
- [x] Step 11: [highlight the category pane and the method pane] "Our method was now created and saved. To finish up, we want to clean up a little and move the method into the right category. To do so, right click into the category list and select the "Add Category" item."
- [x] Step 12: [explanation without highlight below the prompt] "The initialize method typically goes into the "initialize-release" category. Enter this name, the hit Accept."
- [x] Step 13: [centered explanation with only dark background] "Congratulations! You created your first class, in a new category, added a method to it and categorized it correctly. Now we can get started to do some real coding"

This, for now, only applies to steps that can be implemented with the current system.

**Comment by deeps96** [comment]
e6b10fb83661525a71c40935f7c34e6720770f4a
